[workspace]
resolver = "2"
members = [
    "libs/client_lib",
    "libs/server_lib",
    "libs/shared_lib",
    "bins/desktop_client",
#    "bins/web_client",
    "bins/server",
]

[profile.dev.package."*"]
opt-level = 3

[patch.crates-io]
#bevy = { git = "https://github.com/bevyengine/bevy//" }
#bevy_rapier2d = { git = "https://github.com/mvlabat/bevy_rapier.git", branch = "bevy-master" }
#bevy_webgl2 = { path = "../bevy_webgl2" }
bevy_networking_turbulence = { git = "https://github.com/smokku/bevy_networking_turbulence.git" }

#[patch.'https://github.com/bevyengine/bevy']
#bevy = { git = "https://github.com/bevyengine/bevy//" }
