[workspace]
members = [
    "bins/desktop_client",
    "bins/web_client",
    "bins/server",
]

[patch.crates-io]
bevy = { git = "https://github.com/mvlabat/bevy.git", branch = "fix-material-handles-rebased" }
bevy_rapier3d = { git = "https://github.com/mvlabat/bevy_rapier.git", branch = "bevy-master" }
