[package]
name = "mr_desktop_client"
version = "0.1.0"
authors = ["mvlabat <mvlabat@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mr_client_lib = { path = "../../libs/client_lib" }
env_logger = "0.8.1"

[dependencies.bevy]
version = "0.4"
